function [W,RHS] = PendulumODEMatrices(in1,F,in3)
%PENDULUMODEMATRICES
%    [W,RHS] = PENDULUMODEMATRICES(IN1,F,IN3)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Feb-2020 13:44:48

L = in3(3,:);
M = in3(2,:);
dtheta1 = in1(5,:);
dtheta2 = in1(6,:);
dx = in1(4,:);
g = in3(4,:);
m = in3(1,:);
theta1 = in1(2,:);
theta2 = in1(3,:);
t2 = cos(theta1);
t3 = L.^2;
t4 = cos(theta2);
t5 = theta1-theta2;
t6 = cos(t5);
t7 = M.*t3.*t6;
W = reshape([M.*2.0+m,L.*M.*t2.*-2.0,-L.*M.*t4,L.*M.*t2.*-2.0,M.*t3.*2.0,t7,-L.*M.*t4,t7,M.*t3],[3,3]);
if nargout > 1
    t8 = sin(theta1);
    t9 = sin(theta2);
    t10 = sin(t5);
    RHS = [F;-L.*M.*(g.*t8.*2.0+dtheta1.*dx.*t8.*2.0-L.*dtheta1.*dtheta2.*t10);-L.*M.*(g.*t9+dtheta2.*dx.*t9+L.*dtheta1.*dtheta2.*t10)];
end
