function [out1,out2] = PendulumPosition(in1,L)
%PENDULUMPOSITION
%    [OUT1,OUT2] = PENDULUMPOSITION(IN1,L)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Feb-2020 13:44:47

theta1 = in1(2,:);
theta2 = in1(3,:);
x = in1(1,:);
t2 = sin(theta1);
t3 = cos(theta1);
out1 = [x-L.*t2;-L.*t3];
if nargout > 1
    out2 = [x-L.*t2-L.*sin(theta2);-L.*t3-L.*cos(theta2)];
end
